// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRzjUhbV8HuS2qvx6Gtit440DK2jIOQ80',
    appId: '1:98661184009:web:4b1dcd7626c7d190f67ed8',
    messagingSenderId: '98661184009',
    projectId: 'reli-916f0',
    authDomain: 'reli-916f0.firebaseapp.com',
    storageBucket: 'reli-916f0.appspot.com',
    measurementId: 'G-XFLMS52QC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3cbrDslsPSogmjwVfGNZZNTvjFRHLrc4',
    appId: '1:98661184009:android:d5ebb29bb8743b19f67ed8',
    messagingSenderId: '98661184009',
    projectId: 'reli-916f0',
    storageBucket: 'reli-916f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC55-6gAIzJPsiXKHndELNe9vdefTUMao',
    appId: '1:98661184009:ios:1f6c58e2535a2758f67ed8',
    messagingSenderId: '98661184009',
    projectId: 'reli-916f0',
    storageBucket: 'reli-916f0.appspot.com',
    iosClientId: '98661184009-ib3s9abftq2g26jm8n9qraai8i8v8l3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.reliFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC55-6gAIzJPsiXKHndELNe9vdefTUMao',
    appId: '1:98661184009:ios:ce87cd87f9fd79cbf67ed8',
    messagingSenderId: '98661184009',
    projectId: 'reli-916f0',
    storageBucket: 'reli-916f0.appspot.com',
    iosClientId: '98661184009-q4hbpajj7b70n1hsf6kvvv88ae3epfgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.reliFlutterApp.RunnerTests',
  );
}
